# Generated by Django 5.1.6 on 2025-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactinfo_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='message',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='sub_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
