# Generated by Django 5.1.6 on 2025-05-26 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_contactinfo_message_contactinfo_sub_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
