# Generated by Django 5.1.6 on 2025-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contactus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
