# Generated by Django 5.1.6 on 2025-05-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contactinfo_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
