# Generated by Django 5.1.6 on 2025-06-23 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_depth_product_each_box_contains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
