# Generated by Django 5.1.6 on 2025-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
