# Generated by Django 5.1.6 on 2025-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_hot_deal_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='black_friday_deal',
            field=models.BooleanField(default=False),
        ),
    ]
